[build]
builder = "DOCKERFILE"
dockerfilePath = "../../Dockerfile"
buildArgs = {APP_NAME = "aurea"}

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3